/* Team Facilities Management */

/* Classroom Table */
CREATE TABLE Classroom (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CAPACITY INTEGER NOT NULL,
  ROOM INTEGER NOT NULL,
  BUILDING INTEGER NOT NULL
);

/* Reservation Table */
CREATE TABLE Reservation (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CLASSROOM_ID INTEGER NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  START_TIME INTEGER NOT NULL,
  END_TIME INTEGER NOT NULL,
  ACTIVE BOOLEAN,
  SEMESTER_ID INTEGER NOT NULL,
  FOREIGN KEY (CLASSROOM_ID) REFERENCES Classroom(ID)
);

/* Device Table */
CREATE TABLE Device (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CLASSROOM_ID INTEGER NOT NULL,
  STUDENT_ID INTEGER NOT NULL,
  STUDENT_NAME VARCHAR NOT NULL,
  RESERVED BOOLEAN,
  CONDITION VARCHAR,
  RETURN_DATE DATE,
  FOREIGN KEY (CLASSROOM_ID) REFERENCES Classroom(ID)
);